### ISSUE TITLE
Updated version? Issues + performance

### ISSUE THREAD

**Issue by fedor57** [notani/python-glad#1]
Hi, I was excited to find your Whitehill GLAD implementation and played a little bit with it. I found that multiclassification variant glad.py needs some fixes to be able to run. I made it but generally there a couple of problems:
- it works seriously slow, like 10 hours on server for 200k source labels. It somehow crashes on full dataset with 1.3M labels
- some warnings for exponent overflow and division by zero

Generally after the calculation I am not sure that I got some correct results. Labels have a lots classes with equal probabilities. Alpha distibution has lots of negative values while default is 1.0, beta a lot of with >>2.0. Not sure if it is right.

I can see that a lot of efforts have been put into this implementation so I guess there is a more correct version somewhere that is not commited to github? Could you please comment on this?

Thank you a lot!

**Comment by notani** [comment]
Hi, thanks for contacting.  This implementation is just for learning how GLAD works.  So I focused on the readability rather than the stability and efficiency.  (You could improve it by using numpy matrix computation more.)  If you're interested in using GLAD for your work, you might want to try Whitehill's C Implementation available from [his website](https://users.wpi.edu/~jrwhitehill/).

**Comment by fedor57** [comment]
Oh, cool, thanx, this might be very useful! The only thing that this implementation lacks is multilabel mode. But in my case it's not true multilabel but some of "grey" between "black" and "white". I may find a right way to hack binary algorithm for the trinary judgements.

Another point of improvement that can be used for production is a kind of "incremental" fast mode. When we add some new judgements and some new workers. For this case a single iteration that starts with backed up alpha and beta distribution could be sufficient. But also this one could be too long, so perhaps it's worth to implement partial iteration when you skip workers and labels that were not affected by the new data.

**Comment by notani** [comment]
Thanks for your suggestion for speeding up!

There are some algorithms proposed for ordinal labels like white->gray->black. For example, see Zhou et al., Aggregating Ordinal Labels from Crowds by Minimax Conditional Entropy. ICML2014. The implementation can be found at [the author's website](https://dennyzhou.github.io/).
